spring:
    application:
        name: sma
    
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        url: jdbc:mysql://localhost:3306/sma
        password: 1234
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
                use_sql_comments: true
                show_sql: true
        hibernate:
            ddl-auto: create
